class SPM
{
	tag = "SPM";
	class functions
	{
		file = "SPM";
		class spawnManagerPreInit { preInit = 1; };
		class strongpointPreInit { preInit = 1; };
		class missionPreInit { preInit = 1; };
		class categoryForcePreInit { preInit = 1; };
		class categoryAirDefensePreInit { preInit = 1; };
		class categoryAirPatrolPreInit { preInit = 1; };
		class categoryTransportPreInit { preInit = 1; };
		class transportRequestGroundPreInit { preInit = 1; };
		class transportRequestAirPreInit { preInit = 1; };
		class categoryInfantryGarrisonPreInit { preInit = 1; };
		class categoryInfantryPatrolPreInit { preInit = 1; };
		class categoryArmorIdlePreInit { preInit = 1; };
		class categoryArmorPreInit { preInit = 1; };
		class categoryCivilianVehiclesPreInit { preInit = 1; };
		class categoryProvideGarrisonUnitPreInit { preInit = 1; };
		class categoryGuardObjectiveObjectPreInit { preInit = 1; };
		class chainPreInit { preInit = 1; };
		class commandPreInit { preInit = 1; };
		class counterattackPreInit { preInit = 1; };
		class curatorLightPreInit { preInit = 1; };
		class groupFromClasses {};
		class groupFromConfig {};
		class groupFromVehicleCrew {};
		class missionInterceptConvoyPreInit { preInit = 1; };
		class missionMessagesPreInit { preInit = 1; };
		class missionRaidTownPreInit { preInit = 1; };
		class missionRescueHostagesPreInit { preInit = 1; };
		class objectiveCaptureConvoyVehiclePreInit { preInit = 1; };
		class objectiveCaptureManPreInit { preInit = 1; };
		class objectiveCompoundPreInit { preInit = 1; };
		class objectiveDebriefManPreInit { preInit = 1; };
		class objectiveDeliverManPreInit { preInit = 1; };
		class objectiveRescueManPreInit { preInit = 1; };
		class objectiveInteractObjectPreInit { preInit = 1; };
		class objectiveInteractObjectConvoyVehiclePreInit { preInit = 1; };
		class objectiveInteractObjectSimplePreInit { preInit = 1; };
		class objectiveInterceptVehiclePreInit { preInit = 1; };
		class objectiveDestroyObjectPreInit { preInit = 1; };
		class objectiveDestroyAmmoDumpPreInit { preInit = 1; };
		class objectiveDestroyRadioTowerPreInit { preInit = 1; };
		class objectiveDestroyVehiclePreInit { preInit = 1; };
		class objectiveProtectCiviliansPreInit { preInit = 1; };
		class occupyEnter {};
		class occupyGetBuildings {};
		class occupyPreInit { preInit = 1;  };
		class patrolBuildings {};
		class patrolIntersections {};
		class patrolPerimeter {};
		class patrolPreInit { preInit = 1; };
		class patrolRoads {};
		class roadFollow {};
		class spawnGroup {};
		class spawnMineField {};
		class spawnPreInit { preInit = 1; };
		class spawnVehicle {};
		class specialOperationsCommandPreInit { preInit = 1; };
		class strongpointGetChain {};
		class strongpointMapPreInit { preInit = 1; };
		class strongpointNavigationPreInit { preInit = 1; };
		class strongpointUtilPreInit { preInit = 1; };
		class tracePreInit { preInit = 1; };
		class vehicleCaptureParametersPreInit { preInit = 1; };
	};
};
