class JB
{
	tag = "JB";
	class functions
	{
		file = "JB";
		class ammoInit {};
		class ammoInitPlayer {};
		class ammoInitTrolley {};
		class ammoPreInit { preInit = 1; };
		class chatAddEventHandler {};
		class chatPreInit { preInit = 1; };
		class chatRemoveEventHandler {};
		class clearVehicleInventory {};
		class clearVehicleInventoryCondition {};
		class criticalSectionCreate;
		class criticalSectionEnter;
		class criticalSectionLeave;
		class displayName {};
		class distanceToArea {};
		class downgradeATEquipment {};
		class downgradeATInventory {};
		class ejectDeadBodies {};
		class ejectVehicleFromTriggerArea {};
		class ejectVehicleFromTriggerAreaCondition {};
		class flipVehicle {};
		class flipVehicleCondition {};
		class flipVehiclePreInit { preInit = 1; };
		class fuelInitPlayer {};
		class fuelInitSupply {};
		class fuelPreInit { preInit = 1; };
		class getAnimationState {};
		class getInPoints {};
		class halo {};
		class haloInit {};
		class haloPreInit { preInit = 1; };
		class increasedFuelConsumption {};
		class limitSpeed {};
		class matchAnimationState {};
		class medicalPreInit { preInit = 1; };
		class medicalInit {};
		class medicalInitAmbulance {};
		class negatedTypeFilter {};
		class passesTypeFilter {};
		class paradropSlungCargo {};
		class popCargoChute {};
		class randomIndexFromWeightedArray {};
		class randomItemFromWeightedArray {};
		class remoteCall { };
		class remoteCallPreInit { preInit = 1; };
		class repackInit {};
		class repairInit {};
		class repairPreInit { preInit = 1; };
		class respawnVehicleInitialize {};
		class respawnVehiclePreInit { preInit = 1; };
		class respawnVehicleReturn {};
		class respawnVehicleWhenAbandoned {};
		class respawnVehicleWhenKilled {};
		class restrictedTargeting {};
		class serviceVehicle {};
		class setVehicleVarName {};
		class side {};
		class taruPodInit {};
		class taruPodPreInit { preInit = 1; };
		class teleportToTrigger {};
		class timeoutWaitUntil {};
		class tokenizePreInit { preInit = 1; };
		class tokenizeString {};
		class trimWhitespace {};
		class unitWhiteListBlackList {};
		class unitClusters {};
		class weaponSwayInit {};
	};
};